SELECT CL.NUME+' '+CL.PRENUME AS CLIENT,
		C.NUME_CATEGORIE,
		OP.NUME+' '+CL.PRENUME AS OPERATOR,
		P.NUME_PRODUS,I.*,CL.*,C.*,P.*,
		SUMA_ACHITARE-GAJ AS RAMAS
FROM CLIENT CL INNER JOIN IMPRUMUT I ON CL.CLIENT_ID=I.CLIENT_ID
			   INNER JOIN CATEGORIE C ON C.CATEGORIE_ID=I.CATEGORIE_ID
			   INNER JOIN OPERATOR OP ON OP.OPERATOR_ID=I.OPERATOR_ID
			   INNER JOIN PRODUS P ON P.PRODUS_ID=I.PRODUS_ID
ORDER BY I.DATA_ELIBERARII


		