INSERT INTO CLIENT(NUME_CLIENT,NR_TEL)
VALUES(:NUME_CLIENT,:NR_TEL)

SELECT CLIENT_ID
FROM CLIENT WHERE NUME_CLIENT='MORARI ANDREI'

INSERT INTO COMANDA(DENUMIRE,CANTITATE,SPALAT,CALCAT,DATA_INREG,DATA_INTOARC,CLIENT_ID,OPERATOR_ID,PRET,ACTIV)
VALUES(:DENUMIRE,:CANTITATE,:SPALAT,:CALCAT,:DATA_INREG,:DATA_INTOARC,:CLIENT_ID,:OPERATOR_ID,:PRET,:ACTIV)

DELETE CLIENT WHERE CLIENT_ID=18
DELETE COMANDA WHERE COMANDA_ID>=10 AND COMANDA_ID<17

SELECT NUME_CLIENT,NR_TEL FROM CLIENT

SELECT COMANDA_ID
FROM COMANDA WHERE 

SELECT * FROM OPERATOR WHERE USERNAME=:USERNAME AND PAROLA=:PAROLA

SELECT OPERATOR_ID FROM OPERATOR WHERE NUME=:NUME AND PRENUME=:PRENUME

SELECT C.COMANDA_ID,C.DENUMIRE,C.CANTITATE,C.SPALAT,C.CALCAT,C.DATA_INREG,C.DATA_INTOARC,C.PRET,CC.NUME_CLIENT,CC.NR_TEL
FROM COMANDA C INNER JOIN CLIENT CC ON C.CLIENT_ID=CC.CLIENT_ID
WHERE C.COMANDA_ID=:COMANDA_ID

UPDATE COMANDA SET DENUMIRE=:DENUMIRE,CANTITATE=:CANTITATE,SPALAT=:SPALAT,CALCAT=:CALCAT,DATA_INREG=:DATA_INREG,DATA_INTOARC=:DATA_INTOARC,CKIENT_ID=:CLIENT_ID
		PRET=:PRET,ACTIC=:ACTIV,PRET_SPALAT=:PRET_SPALAT,PRET_CALCAT=:PRET_CALCAT
WHERE COMANDA_ID=COMANDA_ID 

			